spring:
  config:
    import: local.yml

  datasource:
    url: jdbc:mariadb://localhost:3306/sss
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password:

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mvc:
    log-request-details: true
logging:
  level:
    org.springframework.web: DEBUG

Spring:
  mvc: