spring:
  config:
    import: local.yml

  datasource:
    url: jdbc:mariadb://localhost:3306/OpenBook
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#logging:
#  level:
#    org:
#      springframework:
#        security : DEBUG