spring:
  config:
    import: local.yml, prompt-template.yml

  datasource:
    url: jdbc:mariadb://localhost:3306/OpenBook
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
  mvc:
    log-request-details: true
logging:
  level:
    org.springframework.web: DEBUG